name: Waka Readme

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '00 00 * * *'
  push:
    branches: ["wakaReadmeCiTest"]
    # ❌ not master: push -> run this workflow -> push update -> run this workflow -> ...

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: cdfmlr/waka-readme-stats@master  # anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: True
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_SHORT_INFO: True
          SHOW_LOC_CHART: True
          SHOW_TOTAL_CODE_TIME: False
          # IGNORED_REPOS: "Rime"
